apiVersion: v1
kind: Service
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: reverse-words
